### PR TITLE
Fix flatpak workflow

### PR DESCRIPTION
**Pull request by Nj0be**

### CODE REVIEW

**Comment by penyuan** [comment]
The Flatpak build seems to fail and is behind builds for other platforms. What seems to be the issue? I'm just a user (not a developer) but happy to help test.

**Comment by 38github** [comment]
I am all for having a distro agnostic build like flatpak working.

**Comment by Nj0be** [comment]
> The Flatpak build seems to fail and is behind builds for other platforms. What seems to be the issue? I'm just a user (not a developer) but happy to help test. 

About a month ago, the HandBrake maintainers updated the "libdovi" dependency, which relies on Cargo for managing Rust dependencies. After this update, the workflow started throwing the following error:

cd "./contrib/libdovi/dovi_tool-libdovi-3.3.1/dolby_vision"; /usr/lib/sdk/rust-stable/bin/cargo fetch
Updating crates.io index
warning: spurious network error (3 tries remaining): [6] Couldn't resolve host name (Could not resolve host: index.crates.io)

error: failed to get `anyhow` as a dependency of package `dolby_vision v3.3.1 (/run/build/handbrake/_flatpak_build/contrib/libdovi/dovi_tool-libdovi-3.3.1/dolby_vision)
Caused by: download of config.json failed 
Caused by: failed to download from `https://index.crates.io/config.json` 
Caused by: [6] Couldn't resolve host name (Could not resolve host: index.crates.io)
make: *** [../contrib/libdovi/module.rules:2: contrib
libdovi/.stamp.libdovi.configure] Error 101
make: *** Waiting for unfinished jobs....

I attempted various solutions to fix the workflow (updating rust, changing dns, changing ubuntu version, etc), but without success. I still don't know the cause of the error.

**Comment by penyuan** [comment]
@Nj0be thank you for explaining. Is there an upstream project (such as SVT-AV1-PSY or Handbrake) where this problem can be raised as an issue?

**Comment by Nj0be** [comment]
> @Nj0be thank you for explaining. Is there an upstream project (such as SVT-AV1-PSY or Handbrake) where this problem can be raised as an issue? 

I don't think so, only the flatpak workflow has this problem but locally it works (at least in my pc). The issue is workflow related but I don't know how to fix it.

**Comment by penyuan** [comment]
> I don't think so, only the flatpak workflow has this problem but locally it works (at least on my pc). The issue is workflow related but I don't know how to fix it.

Ah I see. Interestingly, I see that the "official" nightly Flatpak builds of Handbrake (without SVT-AV1-PSY) also started failing a month ago: 

https://github.com/HandBrake/HandBrake-snapshots/actions/workflows/nightly-linux.yml

I wonder if they're related in any way????? Would it help to raise an issue here? 

https://github.com/HandBrake/HandBrake-snapshots

As a back up option, is it complicated to set up an environment to do local Flatpak builds of `Nj0be/HandBrake-SVT-AV1-PSY`? If not, what are the steps? Is it literally following [the official Handbrake Flatpak instructions](https://handbrake.fr/docs/en/latest/developer/flatpak-repo.html), but using your repository instead?

**Comment by 38github** [comment]
It errors out shortly after `Failed to init: Unable to find sdk org.freedesktop.Sdk version 24.08`

**Comment by Nj0be** [comment]
> It errors out shortly after `Failed to init: Unable to find sdk org.freedesktop.Sdk version 24.08`

The error has changed over time (I’m not sure why). This is an easier problem to fix, and I will try to create a patch soon. Thank you for letting me know.

**Pull request merged**
